// core - custom Language Plugin
// Auto-generated by Forge plugin create

using Forge.Core.Config;
using Forge.Core.Plugin;

namespace core;

/// <summary>
/// custom 語言插件
/// </summary>
public sealed class CustomPlugin : ILanguagePlugin
{
    public PluginCapabilities GetCapabilities()
    {
        return new PluginCapabilities
        {
            LanguageName = "custom",
            SupportedExtensions = new[] { ".custom" },
            SupportsNativeCompilation = true,
            SupportsCrossCompilation = false,
            SupportsInterfaceExtraction = false,
            SupportsGlueGeneration = false,
            SupportedTargets = new[] { "native" }
        };
    }

    public async Task<CompileResult> CompileAsync(
        ValidatedModuleConfig module,
        CompileConfig config,
        CancellationToken ct = default)
    {
        var logs = new List<string>();
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();

        // [DEMO] Custom compilation logic would be implemented here
        logs.Add($"[custom] Compiling module '{module.Config.Name}'");

        stopwatch.Stop();
        return CompileResult.Success(Array.Empty<string>(), logs, stopwatch.Elapsed);
    }

    public Task<InterfaceDescription?> ExtractInterfaceAsync(
        string artifactPath,
        CancellationToken ct = default)
    {
        // [DEMO] Interface extraction for .custom files is not implemented in this demo
        return Task.FromResult<InterfaceDescription?>(null);
    }

    public GlueCodeResult GenerateGlue(InterfaceDescription sourceInterface, string targetLanguage)
    {
        return GlueCodeResult.Failure($"Glue generation not supported for custom");
    }

    public async Task<(bool Available, string Message)> ValidateToolchainAsync(CancellationToken ct = default)
    {
        // [DEMO] Assume custom toolchain is always available for this demo
        return (true, "custom toolchain available");
    }
}