// core - custom Language Plugin
// Auto-generated by Forge plugin create

using Forge.Core.Config;
using Forge.Core.Plugin;

namespace core;

/// <summary>
/// custom 語言插件
/// </summary>
public sealed class CustomPlugin : ILanguagePlugin
{
    public PluginCapabilities GetCapabilities()
    {
        return new PluginCapabilities
        {
            LanguageName = "custom",
            SupportedExtensions = new[] { ".custom" },
            SupportsNativeCompilation = true,
            SupportsCrossCompilation = false,
            SupportsInterfaceExtraction = false,
            SupportsGlueGeneration = false,
            SupportedTargets = new[] { "native" }
        };
    }

    public async Task<CompileResult> CompileAsync(
        ValidatedModuleConfig module,
        CompileConfig config,
        CancellationToken ct = default)
    {
        var logs = new List<string>();
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();

        // 1. Validate toolchain
        var (ok, msg) = await ValidateToolchainAsync(ct);
        if (!ok) { stopwatch.Stop(); return CompileResult.Failure(msg, logs, stopwatch.Elapsed); }
        logs.Add($"[custom] Using: {msg}");

        // 2. Find source files
        var srcDir = Path.Combine(module.ModulePath, "src");
        if (!Directory.Exists(srcDir)) srcDir = module.ModulePath;

        var files = Directory.GetFiles(srcDir, "*.custom", SearchOption.AllDirectories);
        if (files.Length == 0) { stopwatch.Stop(); return CompileResult.Failure("No .custom source files found", logs, stopwatch.Elapsed); }

        // 3. Compile each source file
        var outputDir = Path.Combine(module.OutputPath ?? module.ModulePath, "bin");
        Directory.CreateDirectory(outputDir);
        var artifacts = new List<string>();

        foreach (var f in files)
        {
            var outFile = Path.Combine(outputDir, Path.GetFileNameWithoutExtension(f) + ".o");
            // Configure your compiler command here:
            var (exitCode, stdout, stderr) = await ProcessRunner.RunAsync(
                "custom-compiler", $"\"{f}\" -o \"{outFile}\"", module.ModulePath, ct);
            logs.Add($"[custom] {Path.GetFileName(f)} → exit={exitCode}");
            if (!string.IsNullOrEmpty(stdout)) logs.Add(stdout);
            if (exitCode != 0)
            {
                stopwatch.Stop();
                return CompileResult.Failure($"Compilation failed for {Path.GetFileName(f)}: {stderr}", logs, stopwatch.Elapsed);
            }
            artifacts.Add(outFile);
        }

        stopwatch.Stop();
        return CompileResult.Success(artifacts.ToArray(), logs, stopwatch.Elapsed);
    }

    public async Task<InterfaceDescription?> ExtractInterfaceAsync(
        string artifactPath,
        CancellationToken ct = default)
    {
        if (!File.Exists(artifactPath)) return null;
        var exports = (await NativeSymbolExtractor.ExtractFromBinaryAsync(artifactPath, "custom", ct)).ToArray();
        if (exports.Length == 0) return null;

        return new InterfaceDescription
        {
            Version = "1.0",
            Module = new InterfaceModule
            {
                Name = Path.GetFileNameWithoutExtension(artifactPath),
                Version = "1.0.0"
            },
            Language = new InterfaceLanguage { Name = "custom", Abi = "native", Mode = "native" },
            Exports = exports
        };
    }

    public GlueCodeResult GenerateGlue(InterfaceDescription sourceInterface, string targetLanguage)
    {
        return GlueCodeResult.Failure($"Glue generation not supported for custom");
    }

    public async Task<(bool Available, string Message)> ValidateToolchainAsync(CancellationToken ct = default)
    {
        var version = await ProcessRunner.GetVersionAsync("custom-compiler", "--version", ct);
        if (version is null)
            return (false, "custom-compiler not found. Please install or configure the custom language toolchain.");
        return (true, $"custom-compiler {version}");
    }
}