// core - custom Language Plugin
// Auto-generated by Forge plugin create

using Forge.Core.Config;
using Forge.Core.Plugin;

namespace core;

/// <summary>
/// custom 語言插件
/// </summary>
public sealed class CustomPlugin : ILanguagePlugin
{
    public PluginCapabilities GetCapabilities()
    {
        return new PluginCapabilities
        {
            LanguageName = "custom",
            SupportedExtensions = new[] { ".custom" },
            SupportsNativeCompilation = true,
            SupportsCrossCompilation = false,
            SupportsInterfaceExtraction = false,
            SupportsGlueGeneration = false,
            SupportedTargets = new[] { "native" }
        };
    }

    public async Task<CompileResult> CompileAsync(
        ValidatedModuleConfig module,
        CompileConfig config,
        CancellationToken ct = default)
    {
        var logs = new List<string>();
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();

        // 1. Validate toolchain
        var (ok, msg) = await ValidateToolchainAsync(ct);
        if (!ok) { stopwatch.Stop(); return CompileResult.Failure(msg, logs, stopwatch.Elapsed); }
        logs.Add($"[custom] Using: {msg}");

        // 2. Find source files
        var srcDir = Path.Combine(module.ModulePath, "src");
        if (!Directory.Exists(srcDir)) srcDir = module.ModulePath;

        var files = Directory.GetFiles(srcDir, "*.custom", SearchOption.AllDirectories);
        if (files.Length == 0) { stopwatch.Stop(); return CompileResult.Failure("No .custom source files found", logs, stopwatch.Elapsed); }

        // 3. [DEMO] Replace this section with your compiler invocation
        // Example: var r = await ProcessRunner.RunAsync("custom-compiler", $"\"{f}\"", ...);
        logs.Add($"[custom] Found {files.Length} source file(s) — no compiler configured");

        stopwatch.Stop();
        return CompileResult.Failure("No custom compiler configured — edit CompileAsync to add your compiler", logs, stopwatch.Elapsed);
    }

    public Task<InterfaceDescription?> ExtractInterfaceAsync(
        string artifactPath,
        CancellationToken ct = default)
    {
        // [DEMO] Interface extraction for .custom files is not implemented in this demo
        return Task.FromResult<InterfaceDescription?>(null);
    }

    public GlueCodeResult GenerateGlue(InterfaceDescription sourceInterface, string targetLanguage)
    {
        return GlueCodeResult.Failure($"Glue generation not supported for custom");
    }

    public async Task<(bool Available, string Message)> ValidateToolchainAsync(CancellationToken ct = default)
    {
        // [DEMO] Assume custom toolchain is always available for this demo
        return (true, "custom toolchain available");
    }
}